# Generated by Django 2.2 on 2019-04-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0003_event_allday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
    ]
