# Generated by Django 2.2 on 2019-05-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0006_auto_20190508_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rrule',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
    ]
