# Generated by Django 2.2 on 2019-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0007_auto_20190513_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sleepTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='wakeUpTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='workTime',
            field=models.IntegerField(null=True),
        ),
    ]
