# Generated by Django 2.2 on 2019-05-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0009_auto_20190518_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
