# Generated by Django 2.2 on 2019-05-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0012_auto_20190520_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
