# Generated by Django 2.2 on 2019-05-22 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0013_event_recurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sleepTime',
            field=models.TimeField(default=datetime.time(21, 0), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wakeUpTime',
            field=models.TimeField(default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='workOnWeekends',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='workTime',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
