# Generated by Django 2.2 on 2019-05-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPCalendar', '0016_auto_20190522_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#B71C1C', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#7B7B7B', max_length=7),
        ),
    ]
